---
- name: tp4
  hosts: all
  gather_facts: True
  remote_user: root
  become: True
  become_user: root
  become_method: sudo

  vars:
    docker_users:
      - root

  roles:
    - geerlingguy.docker