#SPDX-License-Identifier: MIT-0
---
# tasks file for docker_molecule
- name: Installer les dépendances
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Ajouter la clé GPG officielle de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ajouter le dépôt Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Installer Docker Engine
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Démarrer et activer Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
...

