#SPDX-License-Identifier: MIT-0
---
# tasks file for docker_molecule
- name: Installer les dépendances
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Ajouter la clé GPG officielle de Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ajouter le dépôt Docker
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Installer Docker Engine
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Démarrer et activer Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Pull de l'image geerlingguy/docker-ubuntu2404-ansible
  community.docker.docker_image:
    name: geerlingguy/docker-ubuntu2404-ansible
    tag: latest
    source: pull
...
