---
driver:
  name: docker
platforms:
  - name: test
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    groups:
      - web

